// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplacePublisherDao is the data access object for the table plugin_marketplace_publisher.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplacePublisherDao struct {
	*internal.PluginMarketplacePublisherDao
}

var (
	// PluginMarketplacePublisher is a globally accessible object for table plugin_marketplace_publisher operations.
	PluginMarketplacePublisher = pluginMarketplacePublisherDao{internal.NewPluginMarketplacePublisherDao()}
)

// Add your custom methods and functionality below.
