// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplacePluginTagDao is the data access object for the table plugin_marketplace_plugin_tag.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplacePluginTagDao struct {
	*internal.PluginMarketplacePluginTagDao
}

var (
	// PluginMarketplacePluginTag is a globally accessible object for table plugin_marketplace_plugin_tag operations.
	PluginMarketplacePluginTag = pluginMarketplacePluginTagDao{internal.NewPluginMarketplacePluginTagDao()}
)

// Add your custom methods and functionality below.
