// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplaceReleaseDao is the data access object for the table plugin_marketplace_release.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplaceReleaseDao struct {
	*internal.PluginMarketplaceReleaseDao
}

var (
	// PluginMarketplaceRelease is a globally accessible object for table plugin_marketplace_release operations.
	PluginMarketplaceRelease = pluginMarketplaceReleaseDao{internal.NewPluginMarketplaceReleaseDao()}
)

// Add your custom methods and functionality below.
