// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplaceDownloadEventDao is the data access object for the table plugin_marketplace_download_event.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplaceDownloadEventDao struct {
	*internal.PluginMarketplaceDownloadEventDao
}

var (
	// PluginMarketplaceDownloadEvent is a globally accessible object for table plugin_marketplace_download_event operations.
	PluginMarketplaceDownloadEvent = pluginMarketplaceDownloadEventDao{internal.NewPluginMarketplaceDownloadEventDao()}
)

// Add your custom methods and functionality below.
