// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplaceDocDao is the data access object for the table plugin_marketplace_doc.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplaceDocDao struct {
	*internal.PluginMarketplaceDocDao
}

var (
	// PluginMarketplaceDoc is a globally accessible object for table plugin_marketplace_doc operations.
	PluginMarketplaceDoc = pluginMarketplaceDocDao{internal.NewPluginMarketplaceDocDao()}
)

// Add your custom methods and functionality below.
