// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplaceArtifactDao is the data access object for the table plugin_marketplace_artifact.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplaceArtifactDao struct {
	*internal.PluginMarketplaceArtifactDao
}

var (
	// PluginMarketplaceArtifact is a globally accessible object for table plugin_marketplace_artifact operations.
	PluginMarketplaceArtifact = pluginMarketplaceArtifactDao{internal.NewPluginMarketplaceArtifactDao()}
)

// Add your custom methods and functionality below.
