// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplaceTagDao is the data access object for the table plugin_marketplace_tag.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplaceTagDao struct {
	*internal.PluginMarketplaceTagDao
}

var (
	// PluginMarketplaceTag is a globally accessible object for table plugin_marketplace_tag operations.
	PluginMarketplaceTag = pluginMarketplaceTagDao{internal.NewPluginMarketplaceTagDao()}
)

// Add your custom methods and functionality below.
