// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplaceVisibilityGrantDao is the data access object for the table plugin_marketplace_visibility_grant.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplaceVisibilityGrantDao struct {
	*internal.PluginMarketplaceVisibilityGrantDao
}

var (
	// PluginMarketplaceVisibilityGrant is a globally accessible object for table plugin_marketplace_visibility_grant operations.
	PluginMarketplaceVisibilityGrant = pluginMarketplaceVisibilityGrantDao{internal.NewPluginMarketplaceVisibilityGrantDao()}
)

// Add your custom methods and functionality below.
