// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplacePluginReadModelDao is the data access object for the table plugin_marketplace_plugin_read_model.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplacePluginReadModelDao struct {
	*internal.PluginMarketplacePluginReadModelDao
}

var (
	// PluginMarketplacePluginReadModel is a globally accessible object for table plugin_marketplace_plugin_read_model operations.
	PluginMarketplacePluginReadModel = pluginMarketplacePluginReadModelDao{internal.NewPluginMarketplacePluginReadModelDao()}
)

// Add your custom methods and functionality below.
