// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplaceCredentialDao is the data access object for the table plugin_marketplace_credential.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplaceCredentialDao struct {
	*internal.PluginMarketplaceCredentialDao
}

var (
	// PluginMarketplaceCredential is a globally accessible object for table plugin_marketplace_credential operations.
	PluginMarketplaceCredential = pluginMarketplaceCredentialDao{internal.NewPluginMarketplaceCredentialDao()}
)

// Add your custom methods and functionality below.
