// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplacePluginDao is the data access object for the table plugin_marketplace_plugin.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplacePluginDao struct {
	*internal.PluginMarketplacePluginDao
}

var (
	// PluginMarketplacePlugin is a globally accessible object for table plugin_marketplace_plugin operations.
	PluginMarketplacePlugin = pluginMarketplacePluginDao{internal.NewPluginMarketplacePluginDao()}
)

// Add your custom methods and functionality below.
