// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplaceDisplayI18nDao is the data access object for the table plugin_marketplace_display_i18n.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplaceDisplayI18nDao struct {
	*internal.PluginMarketplaceDisplayI18nDao
}

var (
	// PluginMarketplaceDisplayI18n is a globally accessible object for table plugin_marketplace_display_i18n operations.
	PluginMarketplaceDisplayI18n = pluginMarketplaceDisplayI18nDao{internal.NewPluginMarketplaceDisplayI18nDao()}
)

// Add your custom methods and functionality below.
