// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplaceRiskDao is the data access object for the table plugin_marketplace_risk.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplaceRiskDao struct {
	*internal.PluginMarketplaceRiskDao
}

var (
	// PluginMarketplaceRisk is a globally accessible object for table plugin_marketplace_risk operations.
	PluginMarketplaceRisk = pluginMarketplaceRiskDao{internal.NewPluginMarketplaceRiskDao()}
)

// Add your custom methods and functionality below.
