// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"linapro-plugin-marketplace/backend/internal/dao/internal"
)

// pluginMarketplaceDownloadSessionDao is the data access object for the table plugin_marketplace_download_session.
// You can define custom methods on it to extend its functionality as needed.
type pluginMarketplaceDownloadSessionDao struct {
	*internal.PluginMarketplaceDownloadSessionDao
}

var (
	// PluginMarketplaceDownloadSession is a globally accessible object for table plugin_marketplace_download_session operations.
	PluginMarketplaceDownloadSession = pluginMarketplaceDownloadSessionDao{internal.NewPluginMarketplaceDownloadSessionDao()}
)

// Add your custom methods and functionality below.
