// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package role

import (
	"lina-core/api/role"
	rolesvc "lina-core/internal/service/role"
)

// ControllerV1 is the role controller.
type ControllerV1 struct {
	roleSvc rolesvc.Service // role service
}

// NewV1 creates and returns a new role controller instance.
func NewV1(roleSvc rolesvc.Service) role.IRoleV1 {
	return &ControllerV1{
		roleSvc: roleSvc,
	}
}
