// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package config

import (
	"lina-core/api/config"
	"lina-core/internal/service/sysconfig"
)

// ControllerV1 implements the config API controller.
type ControllerV1 struct {
	sysConfigSvc sysconfig.Service // sysConfigSvc manages system configuration CRUD.
}

// NewV1 creates and returns a new config controller.
func NewV1(sysConfigSvc sysconfig.Service) config.IConfigV1 {
	return &ControllerV1{
		sysConfigSvc: sysConfigSvc,
	}
}
