// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

// Package market implements marketplace HTTP controllers for the plugin marketplace.
package market

import (
	"linapro-plugin-marketplace/backend/api/market"
	marketplacesvc "linapro-plugin-marketplace/backend/internal/service/marketplace"

	"lina-core/pkg/plugin/capability/bizctxcap"
)

// ControllerV1 is the marketplace HTTP controller.
type ControllerV1 struct {
	marketSvc marketplacesvc.Service
	bizCtx    bizctxcap.Service
}

// NewV1 creates a marketplace controller with explicit runtime dependencies.
func NewV1(marketSvc marketplacesvc.Service, bizCtx bizctxcap.Service) market.IMarketV1 {
	return &ControllerV1{
		marketSvc: marketSvc,
		bizCtx:    bizCtx,
	}
}
