// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

// Package usermsg implements the current-user inbox HTTP API. Handlers map
// authenticated identity onto notify inbox operations and localize category
// display fields for the workbench message surface.
package usermsg
