import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  quickSidebar: [
    {
      type: 'autogenerated',
      dirName: 'quick',
    },
  ],
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'docs',
    },
  ],
  
  communitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'community',
    },
  ],
};

export default sidebars;
