import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 需要按照版本区分的文档
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  quickSidebar: [
    {
      type: 'autogenerated',
      dirName: 'quick',
    },
  ],
};

export default sidebars;
